version: 2.1

workflows:
  main:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: trunk
          context: org-global
  weekly-update:
    triggers:
      - schedule:
          cron: "0 10 * * 1"
          filters:
            branches:
              only: trunk
    jobs:
      - build:
          filters:
            branches:
              only: trunk
      - publish:
          requires:
            - build
          filters:
            branches:
              only: trunk
          context: org-global

jobs:
  build:
    docker:
      - image: cimg/base:2020.09
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build images"
          command: ./build-images.sh

  publish:
    docker:
      - image: cimg/base:2020.09
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build images"
          command: ./build-images.sh
      - run:
          name: "Publish images to Docker Hub if neccessary"
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push cibuilds/snapcraft:core
            docker push cibuilds/snapcraft:core16
            docker push cibuilds/snapcraft:core18
            docker push cibuilds/snapcraft:core20
